### ISSUE TITLE
SNMPv3 error

### ISSUE THREAD

**Issue by GitHub2022** [Cacti/spine#246]
Hi, all my devices are SNMPv3 - AES 128. But for all devices i get the following error: SNMP: Error DES is no longer supported on this system

Also the database is not beeing updated with new values. 

Downloaded and compiled the latest version on a fedora system - 35 Server.

**Comment by netniV** [comment]
I believe that this is a duplicate of #229, make sure that you have cleaned, bootstrapped and configure'd before attempting to make again.

**Comment by GitHub2022** [comment]
Yes i did - just did it again - compile process doesnt throw any errors. 

When i run the command directly "/usr/local/spine/bin/spine -R -S -V 3" i see that there are a lot of timeouts and it complains all the time regarding des is not supported any more. 

Total[3.3143] Device[367] INFO: SNMP Device 'x.x.x.x' has timeout 500000 (500), retries 3
Total[3.3144] Device[295] INFO: SNMP Device 'x.x.x.x' has timeout 500000 (500), retries 3
Total[3.3196] Device[400] HT[1] DS[2498] TT[79.01] SCRIPT: perl /usr/share/cacti/scripts/ping.pl 'x.x.x.x', output: 15.8
Total[3.3198] Device[400] INFO: SNMP Device 'x.x.x.x' has timeout 500000 (500), retries 3
Total[3.3525] SNMP: Error DES is no longer supported on this system
Total[3.3567] Device[362] HT[1] Total Time: 0.35 Seconds
Total[3.3578] Device[392] HT[1] DQ[1] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 4657622800 < output: 4657631000)
Total[3.3588] Device[392] HT[1] NOTE: There are '3' Polling Items for this Device
Total[3.3682] Device[401] HT[1] DQ[1] RECACHE OID: .1.3.6.1.2.1.1.3.0, (assert: 4722862100 < output: 4722866900)
Total[3.3691] Device[401] HT[1] NOTE: There are '5' Polling Items for this Device
Total[3.3693] SNMP: Error DES is no longer supported on this system
Total[3.3707] Device[400] HT[1] Total Time: 0.34 Seconds
Total[3.3929] Device[371] Checking for System Information Update
Total[3.3930] Device[371] Updating Full System Information Table
Total[3.4060] Device[392] HT[1] DS[2476] TT[47.04] SCRIPT: perl /usr/share/cacti/scripts/ping.pl 'x.x.x.x', output: 9.32
Total[3.4062] Device[392] INFO: SNMP Device 'x.x.x.x' has timeout 500000 (500), retries 3

With the regular cmd.php it is working.

**Comment by GitHub2022** [comment]
i used this tutorial to install spine: https://medium.com/make-it-easy/how-to-install-spine-for-cacti-on-ubuntu-20-04-b1bc4c75c502

**Comment by GitHub2022** [comment]
using this version: cacti-spine-1.2.19 with cacti 1.2.20

**Comment by TheWitness** [comment]
Run this one:

```sql
SELECT snmp_priv_protocol FROM host WHERE id = 392;
```

According to the code, it's coming back DES, which has been compiled out of the latest Net-SNMP.

**Comment by TheWitness** [comment]
So, if you want DES support, you will have to compile Net-SNMP yourself.

**Comment by GitHub2022** [comment]
MariaDB [cactidb]> SELECT snmp_priv_protocol FROM host WHERE id = 392;
+--------------------+
| snmp_priv_protocol |
+--------------------+
| AES128             |
+--------------------+

**Comment by GitHub2022** [comment]
No i dont want to use DES. I guess this might be a problem with spine.

**Comment by GitHub2022** [comment]
In the database table poller_item there is only the first entry changed to AES128. All the other entries are remaining as "DES".

Not sure if this is relevant. 

MariaDB [cactidb]> select host_id,snmp_priv_protocol,arg1 from poller_item where host_id=327;
+---------+--------------------+----------------------------------------------------+
| host_id | snmp_priv_protocol | arg1                                               |
+---------+--------------------+----------------------------------------------------+
|     327 | AES128             | perl /usr/share/cacti/scripts/ping.pl 'x.x.x.x' |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.2                            |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.2                            |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.4                            |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.4                            |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.9                            |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.9                            |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.23                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.23                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.21                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.21                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.20                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.20                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.19                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.19                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.18                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.18                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.17                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.17                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.22                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.22                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.23                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.23                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.24                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.24                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.25                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.25                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.10.26                           |
|     327 | DES                | .1.3.6.1.2.1.2.2.1.16.26                           |
+---------+--------------------+----------------------------------------------------+

**Comment by GitHub2022** [comment]
changing the entry will also only reflect the first row in the database table. So i guess it doesnt interate the change to all poller items.

**Comment by TheWitness** [comment]
Yea, for now, click the "Repopulate Poller Cache" when editing the host.  After 1.2.20, you can run "push_out_hosts.php" to fix this.

**Comment by TheWitness** [comment]
This bit has been fixed in the 1.2.x branch.

**Comment by GitHub2022** [comment]
well, i did run the "Repopulate Poller Cache"  several times. I also installed the latest available branch from github. The problem is still the same.

**Comment by TheWitness** [comment]
push_out_hosts.php
