### ISSUE TITLE
Re-Index update query failed due to lack of escaping

### ISSUE THREAD

**Issue by resetsa** [Cacti/spine#49]
2018.02.13 10:32:06 - SPINE: Poller[1] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Ethernet0/7' interface' WHERE host_id='16' AND data_query_id='1' AND arg1='.1.3.' at line 1', SQL Fragment:'UPDATE poller_reindex SET assert_value='Adaptive Security Appliance 'Ethernet0/7' interface' WHERE host_id='16' AND data_query_id='1' AND arg1='.1.3.6.1.2.1.2.2.1.2.10''
--
2018.02.13 10:32:05 - SPINE: Poller[1] ERROR: SQL Failed! Error:'1064', Message:'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Ethernet0/7' interface' WHERE host_id='7' AND data_query_id='1' AND arg1='.1.3.6' at line 1', SQL Fragment:'UPDATE poller_reindex SET assert_value='Adaptive Security Appliance 'Ethernet0/7' interface' WHERE host_id='7' AND data_query_id='1' AND arg1='.1.3.6.1.2.1.2.2.1.2.10''

I'm use Cacti 1.1.33 and spine-1.1.35

**Comment by cigamit** [comment]
Resolved now.  Please update poller.c from develop.  It'll be in 1.1.36.

**Comment by stefandewal** [comment]
I have 1.1.38 installed and still receive this message. when chaning the re-index method to uptime i get the same sql error. when i set it to index count it works perfectly

i use cacti 1.1.38/ cacti spine 1.1.38 / Server version: 5.5.56-MariaDB MariaDB Server / centos 7

This my error:

UPDATE poller_reindex SET assert_value='U' WHERE host_id='2' AND data_query_id='2' AND arg1='perl /opt/cacti/scripts/query_unix_partitions.pl 'num_indexes''

it seems the quote problem still persists.
